baseURL = "http://ivan.wip.ac/"
languageCode = "en-us"
title = "The Wip Blog"
theme = "ananke"



DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
enableRobotsTXT = true
show_reading_time = true
omit_header_text = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/ipedrazas"
  instagram = ""
  youtube = ""
  github = "https://github.com/ipedrazas"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
